name: minim
channels:
  - conda-forge
  - microsoft
dependencies:
  # CORE DEPENDENCIES
  - cryptography
  - mutagen
  - requests
  # OPTIONAL DEPENDENCIES
  - ffmpeg
  - flask
  - levenshtein
  - numpy
  - pillow
  - playwright
  # DEVELOPMENT DEPENDENCIES
  - coverage
  - pytest
  - ruff
  # DOCUMENTATION DEPENDENCIES
  - furo
  - ipywidgets
  - jupyterlab
  - myst-nb
  - numpydoc
  - sphinx
  - sphinx-copybutton
  - sphinx-togglebutton