name: continuous integration
on: [push]
env:
  DISCOGS_CONSUMER_KEY: ${{ secrets.DISCOGS_CONSUMER_KEY }}
  DISCOGS_CONSUMER_SECRET: ${{ secrets.DISCOGS_CONSUMER_SECRET }}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  SPOTIFY_SP_DC: ${{ secrets.SPOTIFY_SP_DC }}
  TIDAL_CLIENT_ID: ${{ secrets.TIDAL_CLIENT_ID }}
  TIDAL_CLIENT_SECRET: ${{ secrets.TIDAL_CLIENT_SECRET }}
  TIDAL_PRIVATE_CLIENT_ID: ${{ secrets.TIDAL_PRIVATE_CLIENT_ID }}
  TIDAL_PRIVATE_CLIENT_SECRET: ${{ secrets.TIDAL_PRIVATE_CLIENT_SECRET }}
jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: pip-install-dependencies
        run: python3 -m pip install -r requirements_minimal.txt
      - name: ruff-lint
        run: |
          python3 -m pip install ruff
          ruff check --target-version=py39 .
        continue-on-error: true
      - name: pytest-test
        run: |
          python3 -m pip install pytest
          pytest